//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTSEOnlineExam.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_txn_Test_Completion
    {
        public int Id { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<bool> IsExamCompleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
