//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTSEOnlineExam.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Question()
        {
            this.tbl_Question_Choice = new HashSet<tbl_Question_Choice>();
            this.tbl_Test_Question_Map = new HashSet<tbl_Test_Question_Map>();
        }
    
        public int Id { get; set; }
        public int QuestionCategoryId { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> Points { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> QuestionDifficultyId { get; set; }
    
        public virtual tbl_Question_Category tbl_Question_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Question_Choice> tbl_Question_Choice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Test_Question_Map> tbl_Test_Question_Map { get; set; }
        public virtual tbl_Question_Difficulty_Level tbl_Question_Difficulty_Level { get; set; }
    }
}
